### ISSUE TITLE
War: 勝負済みのFrameについてImageCacheをつかってExpireの画像を表示

### ISSUE THREAD

**Issue by yu23ki14** [senspace-studio/card#40]
Frameの初期画像をCacheのmax-ageで更新できるので、それをつかって終わっているものを読み込んだときにExpireの画像が表示されているようにする。

Expireの条件は
1. 作成から24時間経ったもの（WarContractのgameStatusで4番がExpired、その他ステータスはIWar.solに記載）
2. チャレンジ済みもの（gameStatusで2番）
3. 試合が終わっているもの（gameStatusで3番）

https://docs.farcaster.xyz/reference/frames/spec#images

**Comment by barubora3** [comment]
コチラで対応
https://github.com/senspace-studio/card/pull/51
