### ISSUE TITLE
War: 初期リリースのためにDegenBetのFrameをスキップ & Bettingリリース後のためにNative DEGENをWarでBetできるようにする

### ISSUE THREAD

**Issue by yu23ki14** [senspace-studio/card#41]
こんなかんじ
![image](https://github.com/senspace-studio/card/assets/18475563/c80e0de3-0abb-4ee6-b2e4-85c8c7734962)

**Comment by barubora3** [comment]
コチラで対応
BetのFrameのスキップ、contract定義へのvalueの追加
https://github.com/senspace-studio/card/pull/51
