### ISSUE TITLE
War: bot投稿とtx送信を疎結合にする

### ISSUE THREAD

**Issue by yu23ki14** [senspace-studio/card#55]
GameMade、GameChallengeでうけるwebhookがbot投稿とtx送信が密結合になっており、bot投稿に失敗するとtxが送信されない状態になっている。
Neynarでエラーをはいても、TXは送るようにする。

---

neynarのキャッシュ仕様のためにpublishしたあとにlookupしているのですがこれはセットでお願いします。

**Comment by kunroku** [comment]
ご指摘の問題点はGameMadeでのcreated a new game!の投稿がエラーだとGameChallengedのsendTransactionができないよねということだと思うのですが、お間違い無いですか？
（一応確認ですが、GameChallengedだけを見る場合はsendTransactionの後にcastしているので、Txを送れなかったということはないという認識です。）
これを前提としたとき、created a new game!の投稿が失敗の場合、以降のbotからのcastのreplyToがないのですが、どうすれば良いでしょうか？

**Comment by yu23ki14** [comment]
厳密にいうと以下の事象が置きます

1. GameMadeでpublishCastが失敗すると、this.warService.onGameMadeが発火しなくてDBにゲーム情報が保存されない。
2. GameChallengedでthis.warService.getWarGameByGameIdを実行するが、GameMade時にゲーム情報がDBに保存されてないので取ってこれない。その状態ではトランザクションが送れないのでRevealTXが実行できない。

という感じです。
なので、Neynarで失敗してもDBにゲーム情報が保存されるようにするというのが正しいオーダーですね。質問ありがとうございます。

ちなみに、replyToがつかないのは仕方ないので普通に投稿するので大丈夫です。
