### ISSUE TITLE
All: スマコンの分析用のログについて

### ISSUE THREAD

**Issue by yu23ki14** [senspace-studio/card#59]
Draw: Spin
Card: Transfer
War: GameMade, GameCreated, GameRevealed
WarPool: Pooled（いくらプールされたかも取れるようにする）

**Comment by Apollo716** [comment]
@yu23ki14 
Drawはできれば引いたカードのナンバーも取れると嬉しい（100枚とか一気にDrawする時はデータが見にくくなるか）

> GameMade, GameCreated
これMadeとCreatedって何の違いでしたっけ？

WarはBattleセット、チャレンジ、リザルト全部で賭けたカードの数字もわかるようにしたい

**Comment by yu23ki14** [comment]
WarPoolでデポジットしたときの額をイベントに入れるのを実装
