### ISSUE TITLE
Onboarding: verified address および invite onlyのエラーフレーム追加

### ISSUE THREAD

**Issue by Apollo716** [senspace-studio/card#67]
【MUST】

ここからRule以外のFrame移動はverifiede addressとinvite onlyのFrameエラー追加
（verified address外してDraw押したら先に進めたので確認）
![image](https://github.com/senspace-studio/card/assets/41936657/99047e21-505b-4848-a2ff-f7d919ac0ed2)

**Comment by yu23ki14** [comment]
Done
