### ISSUE TITLE
Onboarding: TopからRule&Inviteページの追加

### ISSUE THREAD

**Issue by Apollo716** [senspace-studio/card#76]
【MUST】

meijiさんからInviteもゲームに重要な要素なので、Onboarding Frameで完結できるようにしたいと提案もらいました
添付画像のように、1のtop Frameの次に、Rule / Inviteを押すと、RuleとInviteのボタンがあるFrameに移動させて欲しいです🙏
2のFrameではruleは外部リンク、InviteはInvite Frameに飛ばす(or Onboarding Frame内にInvite Frame組み込む)をして欲しいです

画像は[こちら](https://drive.google.com/file/d/1O89daEqhMd7GcUlHslK0BEwiUon9CEMX/view?usp=sharing)
![image](https://github.com/senspace-studio/card/assets/41936657/77c0911a-42e9-4ec0-80d5-23e6eaf3ba51)

**Comment by yu23ki14** [comment]
Done
