### ISSUE TITLE
War: Challengeシェアのページが正常に出ないことがある。

### ISSUE THREAD

**Issue by yu23ki14** [senspace-studio/card#89]
このCastのように/war/challenge/{gameId} のページで正常に表示されないことがある。
https://warpcast.com/cardgamemaster/0xaeb3420d

原因は何らかの原因でキャッシュしてるDBへの保存ができておらず、呼び出そうとしたときに存在しないのでこうなっていると思われる。

**Comment by barubora3** [comment]
推測されてる通り、DBにレコードが存在してないことが本事象の原因です。
手動でDBにデータ登録し、改めてFrame Validatorで確認したら正常に表示されるようになりました。

ただ、DB登録に失敗したパターンを考慮して /war/challenge/{gameId} ページ内でDBからデータが取れない場合、コントラクトとNeyar経由でデータを収集して再度登録するようにしてます。
それなのにDBには依然としてデータが存際せず、救済出来てないのが不思議です。
先ほどローカルで試してみたら救済処理は動いていたので、本番環境の環境変数の設定が誤ってる可能性を少し疑っています。
（この救済処理の時だけWar Poolコントラクトを参照しているため、環境変数の`WAR_POOL_CONTRACT_ADDRESS`の値が誤ってるなど）

本番環境の環境変数を確認させていただきたいです
また、本番環境のログって見させてもらう事は可能でしょうか？

**Comment by yu23ki14** [comment]
なるほど！

**Comment by yu23ki14** [comment]
WAR_POOL_CONTRACT_ADDRESSが必要なこと認識してなかったです、今追加しました！

**Comment by yu23ki14** [comment]
こちら治ったのでクローズします
