### ISSUE TITLE
Onboarding: リーダーボードのUpdate

### ISSUE THREAD

**Issue by Apollo716** [senspace-studio/card#96]
【現状】
個人のStack上位3と自分のスコアが表示
【TODO】

- [ ] 個人のStack上位3と自分のスコアが表示（今の実装のままでOK）
- [ ] 試合数上位3と自分のスコア(勝ち-負け-引き分け)を表示 例）apollo716　25-18-7
- [ ] 招待ユーザーのPlay数（※あるプレイヤーが招待したユーザーの総Play数）上位3と自分のスコアが表示

↓のリーダーボードにBackとNext>ボタンがついてリーダーボードが3ページあるイメージデザインはどれも同じで問題ないがカラム名だけ変える必要あるので @Apollo716 がクリエイティブチームに依頼
<img width="511" alt="image" src="https://github.com/senspace-studio/card/assets/41936657/b2c35396-19b9-4516-8b7e-3e4cd9eb59ee">

**Comment by yu23ki14** [comment]
@kunroku 
こちらのデータですが、AWS Lambdaをつかって1日1回バッチ処理できるようにしたいと思います。
ThirdwebEngineのイベントログ取得のエンドポイントをつかって、当該期間の結果を集計しJSONとしてS3に保存するという形になります。
対象期間はバッチ処理時刻から7日間です。

- [ ] Win-Lose-Drawの集計（JSON形式での出力）
- [ ] S3への保存
- [ ] 招待Play数の集計

## プロジェクトディレクトリ

- 新しくbatchというディレクトリをrootに切って、そこに作るようにしてください。実際の関数はその下にsrcなどを掘っていただいてもよいです。
- 下記の必要な関数それぞれファイルを分けて作成してください。共通関数はlibやutilsなどに入れて大丈夫です。

## 必要な関数

### Win.Lose.Draw の集計

勝負が7日前までのものを対象

Maker、Challengerの両方で行った試合について、勝敗結果をアドレスごとに集計。
GameRevealedイベントを使えば集計できるはず。

期待する形式
```
[
  {address: '0x123...', win: 10, lose: 10, draw: 5}
]
```

### 招待者のPlay数

招待送信が14日前までのものを対象
勝負が14日前のものを対象

招待NFTを送った人がPlayした回数をアドレスごとに集計。
Transferイベントと、GameRevealedイベントを組み合わせて集計。
※ 同じアドレスにTransferしている可能性がありその場合は一番早いもの、同じTokenIdをTransferしている可能性がありその場合は一番早いもの。

期待する形式
```
[
  {address: '0x123...', battles: 100}
]
```

**Comment by Apollo716** [comment]
@yu23ki14 
こちらもうcloseしていいですかね？
