### ISSUE TITLE
Cast Action: card scouter typo修正

### ISSUE THREAD

**Issue by Apollo716** [senspace-studio/card#99]
【TODO】

- [ ]❌ /card Scounter → ⭕️/card Scouter に修正

![image](https://github.com/senspace-studio/card/assets/41936657/877dbd74-89d7-4747-86b1-4aead9f6a7cd)

**Comment by yu23ki14** [comment]
@Apollo716 
これってCastActionの名前ですかね？もう治ってるので、インストールしなおしたらいけるかとおもいます。

**Comment by Apollo716** [comment]
@yu23ki14 
了解です！あざます

**Comment by Apollo716** [comment]
@yu23ki14 
了解です！あざます🙏
